version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/ntm-gaming-team-bot/
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: /home/ec2-user/ntm-gaming-team-bot/scripts/deploy.sh
      timeout: 180
      runas: ec2-user
permissions:
  - object: /home/ec2-user/ntm-gaming-team-bot/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory