version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/ntm-gaming-team-bot/
hooks:
  ApplicationStart:
    - location: yarn install && yarn build && yarn production-deploy
      timeout: 180
      runas: ec2-user