version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/ntm-gaming-team-bot/
    owner: ec2-user
hooks:
  ApplicationStart:
    - location: /home/ec2-user/ntm-gaming-team-bot/scripts/deploy.sh
      timeout: 180
      runas: ec2-user